"""increase_email_field_length

Revision ID: 009e5a6a7e86
Revises: b3449f3dbe32
Create Date: 2025-11-13 12:47:59.724855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009e5a6a7e86'
down_revision: Union[str, Sequence[str], None] = 'b3449f3dbe32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_points', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               comment='Может содержать несколько email через запятую',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_points', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Может содержать несколько email через запятую',
               existing_nullable=True)
    # ### end Alembic commands ###
