"""change_reviewed_by_to_int

Revision ID: 019eec32bc63
Revises: 45db8c0b714c
Create Date: 2026-02-12 17:34:27.470593

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '019eec32bc63'
down_revision: Union[str, Sequence[str], None] = '45db8c0b714c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_column('daily_checkins', 'reviewed_by')
    op.add_column('daily_checkins', sa.Column('reviewed_by', sa.Integer(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_checkins', 'reviewed_by',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
