"""add_checkin_moderation_fields

Revision ID: 45db8c0b714c
Revises: 03549ea0f98d
Create Date: 2026-02-12 16:22:55.698769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45db8c0b714c'
down_revision: Union[str, Sequence[str], None] = '03549ea0f98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_checkins', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.add_column('daily_checkins', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('daily_checkins', sa.Column('reject_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_checkins', 'reject_reason')
    op.drop_column('daily_checkins', 'reviewed_at')
    op.drop_column('daily_checkins', 'reviewed_by')
    # ### end Alembic commands ###
