"""increase_phone_mobile_field_length

Revision ID: b3449f3dbe32
Revises: 9d1bd50d6b27
Create Date: 2025-11-13 12:45:07.025942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3449f3dbe32'
down_revision: Union[str, Sequence[str], None] = '9d1bd50d6b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_points', 'phone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               comment='Может содержать несколько номеров через запятую',
               existing_nullable=True)
    op.alter_column('delivery_points', 'mobile',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               comment='Может содержать несколько номеров через запятую',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_points', 'mobile',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Может содержать несколько номеров через запятую',
               existing_nullable=True)
    op.alter_column('delivery_points', 'phone',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Может содержать несколько номеров через запятую',
               existing_nullable=True)
    # ### end Alembic commands ###
