"""add_calculator_models

Revision ID: bc6c4f2244d4
Revises: eaed51cb9bb2
Create Date: 2025-11-13 17:18:04.897363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'bc6c4f2244d4'
down_revision: Union[str, Sequence[str], None] = 'eaed51cb9bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название категории'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='URL-friendly название'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание категории'),
    sa.Column('cost_multiplier', sa.Numeric(precision=5, scale=2), nullable=False, comment='Множитель стоимости (пока не используется)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=True)
    op.create_index(op.f('ix_product_categories_slug'), 'product_categories', ['slug'], unique=True)
    op.create_geospatial_table('distribution_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Название РЦ'),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False, comment='Координаты РЦ'),
    sa.Column('address', sa.Text(), nullable=True, comment='Адрес РЦ'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли РЦ'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_distribution_centers_location', 'distribution_centers', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_distribution_centers_id'), 'distribution_centers', ['id'], unique=False)
    op.create_index(op.f('ix_distribution_centers_name'), 'distribution_centers', ['name'], unique=False)
    op.create_index(op.f('ix_distribution_centers_region_id'), 'distribution_centers', ['region_id'], unique=False)
    op.create_table('region_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('driver_hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False, comment='Стоимость 1 часа работы водителя, руб.'),
    sa.Column('planned_work_hours', sa.Numeric(precision=10, scale=2), nullable=False, comment='Часов на выполнение работы по плану'),
    sa.Column('fuel_price_per_liter', sa.Numeric(precision=10, scale=2), nullable=False, comment='Стоимость бензина, руб/л'),
    sa.Column('fuel_consumption_per_100km', sa.Numeric(precision=10, scale=2), nullable=False, comment='Расход бензина, л/100км'),
    sa.Column('depreciation_coefficient', sa.Numeric(precision=10, scale=4), nullable=False, comment='Коэффициент амортизации авто'),
    sa.Column('warehouse_processing_per_kg', sa.Numeric(precision=10, scale=2), nullable=False, comment='Стоимость обработки 1 кг на РЦ, руб.'),
    sa.Column('service_fee_per_kg', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сервисный сбор 1 кг (выручка компании), руб.'),
    sa.Column('delivery_point_cost', sa.Numeric(precision=10, scale=2), nullable=False, comment='Стоимость одной точки доставки, руб.'),
    sa.Column('standard_trip_weight', sa.Numeric(precision=10, scale=2), nullable=False, comment='Стандартный вес груза в рейсе, кг'),
    sa.Column('standard_box_length', sa.Integer(), nullable=False, comment='Длина эталонной коробки, см'),
    sa.Column('standard_box_width', sa.Integer(), nullable=False, comment='Ширина эталонной коробки, см'),
    sa.Column('standard_box_height', sa.Integer(), nullable=False, comment='Высота эталонной коробки, см'),
    sa.Column('standard_box_max_weight', sa.Numeric(precision=10, scale=2), nullable=False, comment='Максимальный вес эталонной коробки, кг'),
    sa.Column('min_points_for_discount', sa.Integer(), nullable=False, comment='Минимальное количество точек до применения скидки'),
    sa.Column('discount_step_points', sa.Integer(), nullable=False, comment='Шаг прироста количества точек доставки'),
    sa.Column('initial_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False, comment='Стартовая скидка, %'),
    sa.Column('discount_step_percent', sa.Numeric(precision=5, scale=2), nullable=False, comment='Шаг прироста скидки, %'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_pricing_id'), 'region_pricing', ['id'], unique=False)
    op.create_index(op.f('ix_region_pricing_region_id'), 'region_pricing', ['region_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_region_pricing_region_id'), table_name='region_pricing')
    op.drop_index(op.f('ix_region_pricing_id'), table_name='region_pricing')
    op.drop_table('region_pricing')
    op.drop_index(op.f('ix_distribution_centers_region_id'), table_name='distribution_centers')
    op.drop_index(op.f('ix_distribution_centers_name'), table_name='distribution_centers')
    op.drop_index(op.f('ix_distribution_centers_id'), table_name='distribution_centers')
    op.drop_geospatial_index('idx_distribution_centers_location', table_name='distribution_centers', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('distribution_centers')
    op.drop_index(op.f('ix_product_categories_slug'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
