"""change_contact_fields_to_text

Revision ID: eaed51cb9bb2
Revises: 009e5a6a7e86
Create Date: 2025-11-13 13:01:23.250279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaed51cb9bb2'
down_revision: Union[str, Sequence[str], None] = '009e5a6a7e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_points', 'phone',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_comment='Может содержать несколько номеров через запятую',
               existing_nullable=True)
    op.alter_column('delivery_points', 'mobile',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_comment='Может содержать несколько номеров через запятую',
               existing_nullable=True)
    op.alter_column('delivery_points', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_comment='Может содержать несколько email через запятую',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_points', 'email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_comment='Может содержать несколько email через запятую',
               existing_nullable=True)
    op.alter_column('delivery_points', 'mobile',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_comment='Может содержать несколько номеров через запятую',
               existing_nullable=True)
    op.alter_column('delivery_points', 'phone',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_comment='Может содержать несколько номеров через запятую',
               existing_nullable=True)
    # ### end Alembic commands ###
